server:
  port: 8761

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rbnascimentoo/delivery-configs
          
eureka:
   client:
      register-with-eureka : false
      fetch-registry: false